### ISSUE TITLE
Are cooperative tasks hard to train with QMIX?

### ISSUE THREAD

**Issue by GoingMyWay** [semitable/lb-foraging#13]
Dear authors, in cooperative tasks (`-coop`), it seems it is hard to train converged policies with QMIX (the episode rewards are nearly zero). I used the default setting provided by PyMARL and used RLlib to train LBF with QMIX. I found in your paper, you trained `Foraging-2s-8x8-2p-2f-coop-v2` and `Foraging-8x8-2p-2f-coop-v2` with QMIX and the performance were converged.  It would be great if you can provide some suggestions.

**Comment by semitable** [comment]
Dear @GoingMyWay, have you tried our fork of PyMARL (E-PyMARL)? It can be found here: https://github.com/uoe-agents/epymarl with instructions on how to run level based foraging. On the last page of the paper (https://arxiv.org/pdf/2006.07869.pdf), you will also find the exact hyperparameters we used to generate the results on the paper.

**Comment by GoingMyWay** [comment]
@semitable  Dear author, thank you. I will try your code. I tried to use RLlib, which seems hard to train.
