### ISSUE TITLE
Wonder whether step() and reset() only return observation

### ISSUE THREAD

**Issue by dwyzzy** [semitable/lb-foraging#3]
Thank you very much for such a great work!

I hope to know whether the code means it will not return any information about the absolute position of the agents and the food when using step() and reset() in [environment.py](https://github.com/semitable/lb-foraging/blob/master/lbforaging/foraging/environment.py) 

I am looking forward to hearing from you! Thank you! (I'm sorry if I missed somthing important)

**Comment by semitable** [comment]
Hi!

The positions are relative to the controlled agent. In the fully observable setting (default), there should be enough information for an agent to infer its location.

**Comment by dwyzzy** [comment]
Thank you!

I also found that in the older version, the code uses

`row = self.np_random.randint(0, self.rows - 1)
col = self.np_random.randint(0, self.cols - 1)`

to generate players, while in the latest version, the code uses

`row = self.np_random.randint(0, self.rows)
col = self.np_random.randint(0, self.cols)`

to generate players.

I hope to know why there is the change on the range. Thank you!

**Comment by dwyzzy** [comment]
Thank you very much!

**Comment by shark939393** [comment]
how can I set players as q_agent? I want to use other types of agents

**Comment by dwyzzy** [comment]
> how can I set players as q_agent? I want to use other types of agents

Maybe you can refer to these MARL framework:
1. [Python MARL framework(PyMARL)](https://github.com/oxwhirl/pymarl)
2. [Extended Python MARL framework - EPyMARL](https://github.com/uoe-agents/epymarl)
3. [PyMARL2](https://github.com/hijkzzz/pymarl2)
