### ISSUE TITLE
Error , not valid action 

### ISSUE THREAD

**Issue by shark939393** [semitable/lb-foraging#4]
hello I am trying to execute the code , but when I compile it returns me this error
  raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: (5, 4) is not a valid Action

my env is  " env = gym.make("Foraging-10x10-2p-5f-v1") "

Did I set it wrong? 

thank you for all

**Comment by semitable** [comment]
Hi,

Can you include the code that raises this error?

**Comment by shark939393** [comment]
UserWarning: WARN: Box bound precision lowered by casting to float32
  "Box bound precision lowered by casting to {}".format(self.dtype)
Traceback (most recent call last):
  File "lbforaging.py", line 57, in <module>
    main(args.times, args.render)
  File "lbforaging.py", line 45, in main
    _game_loop(env, render)
  File "lbforaging.py", line 28, in _game_loop
    nobs, nreward, ndone, _ = env.step(actions)
  File "/home/maicmania/PycharmProjects/mySmartWasteMARL/venv/lib/python3.6/site-packages/gym/wrappers/order_enforcing.py", line 11, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/maicmania/PycharmProjects/mySmartWasteMARL/lbforaging/foraging/environment.py", line 414, in step
    for p, a in zip(self.players, actions)
  File "/home/maicmania/PycharmProjects/mySmartWasteMARL/lbforaging/foraging/environment.py", line 414, in <listcomp>
    for p, a in zip(self.players, actions)
  File "/usr/lib/python3.6/enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 535, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: (3, 1) is not a valid Action


                    for i, player in enumerate(env.players):
                          actions.append(env.action_space.sample())
line 28 is            nobs, nreward, ndone, _ = env.step(actions)


                for episode in range(game_count):
line 45                   _game_loop(env, render)


line 57 is     main(args.times, args.render)



my env is                      env = gym.make("Foraging-10x10-2p-5f-v1")

and __init__ file is left the same as the one I downloaded from the repository


thanks for your reply.

**Comment by semitable** [comment]
You might be using an older version of `lbforaging.py`..?
In the master branch, the step looks like:
```python
actions = env.action_space.sample()
nobs, nreward, ndone, _ = env.step(actions)
...
```
Essentially you don't need the `actions.append(` or the loop over the players. You just need to step using `env.step(env.action_space.sample())`

**Comment by semitable** [comment]
Looks like it's just a warning. Shouldn't cause any issues.

**Comment by shark939393** [comment]
ok thank you so much

**Comment by shark939393** [comment]
excuse another question, how do I start the simulation? I get a Gui with the apple? which file should I run?

**Comment by semitable** [comment]
You need an agent that can make actions given the environment observation. Training/making such an agent is outside the scope of this repo but we do our best to have a similar API to OpenAI's Gym. You'd just need to run `env.step(_ACTIONS_)` and then `env.render()` to see the simulation. But to find the _actions_ you'd need something outside this repo (e.g. a DQN implementation?).

**Comment by shark939393** [comment]
ah ok , I thought you could simulate and see agents in the environment as in the gif where

**Comment by semitable** [comment]
Yes, you actually can. You still need to select the actions though. I am not sure what the exact question is? :)
Have you tried `python lbforaging.py --render`? lbforaging.py is in the root directory. It might be what you are looking for.

**Comment by shark939393** [comment]
Oh yes, thank you for all
