### ISSUE TITLE
What does the obs of each agent contain?

### ISSUE THREAD

**Issue by GoingMyWay** [semitable/lb-foraging#8]
Hi, what does the obs of each agent contain? It seems there is no introduction in the docs. By reading the code, I guess the obs of each agent contains the position of agent and level etc. I found that the obs can also be fully observable. It would be great if you can update the docs.

**Comment by semitable** [comment]
Thanks for your comment. I will get to updating the README in this repo. In the meantime check Appendix A6 (page 17) in our benchmarking paper here: https://arxiv.org/pdf/2006.07869.pdf

**Comment by GoingMyWay** [comment]
> Thanks for your comment. I will get to updating the README in this repo. In the meantime check Appendix A6 (page 17) in our benchmarking paper here: https://arxiv.org/pdf/2006.07869.pdf

Dear @semitable, thank you.
